// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bclkwjcdyrzlardsvxew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjbGt3amNkeXJ6bGFyZHN2eGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTc1OTUsImV4cCI6MjA1NTgzMzU5NX0.OWkdr7twRwQBB333qqkD04hGYdKzhO-RsH6MSiSDUfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);